FROM php:7.2.0

VOLUME /opt/project

RUN apt-get update

RUN apt-get install -y git

RUN apt-get install -y \
    git \
    libzip-dev \
    zip \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install \
    zip

RUN curl -sS https://getcomposer.org/installer | php \
        && mv composer.phar /usr/local/bin/ \
        && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

WORKDIR /opt/project
